ITEM.name = "Automated External Defibrillator"
ITEM.description = "aedDesc"
ITEM.model = "models/bloocobalt/l4d/items/w_eq_defibrillator.mdl"
ITEM.category = "Medical"
ITEM.price = 15
ITEM.healthPoint = -100 -- Health point that the player will get
ITEM.medAttr = 3 -- How much medical attribute the character needs
ITEM.bleeding = true
ITEM.sound = "ambient/energy/zap9.wav"