ITEM.name = "Rappelling Gear"
ITEM.description = "itemRappellingGearDesc"
ITEM.category = "Utility"
ITEM.model = "models/gibs/metal_gib4.mdl"
ITEM.class = "rappel_gear"
ITEM.weaponCategory = "special"
ITEM.width = 1
ITEM.height = 1
ITEM.factions = {FACTION_MPF, FACTION_OTA}
ITEM.noDeathDrop = true