ENT.Type = "anim"
ENT.PrintName = "Interactive Computer"
ENT.Author = "Frosty"
ENT.Category = "HL2 RP: Computers"
ENT.Spawnable = false
ENT.AdminOnly = false
ENT.PhysgunDisable = true
ENT.bNoPersist = true
ENT.PopulateEntityInfo = true
ENT.RenderGroup = RENDERGROUP_BOTH
