ITEM.name = "Burger"
ITEM.model = "models/dead rising 2/burger.mdl"
ITEM.description = "itemBurgerDesc"
ITEM.hunger = 35
ITEM.thirst = -10
ITEM.price = 50
ITEM.heal = 10
ITEM.cookable = true
ITEM.classes = nil