ITEM.name = "Canned Ham"
ITEM.model = "models/hlvr/food/can_square.mdl"
ITEM.description = "itemCannedHamDesc"
ITEM.hunger = 20
ITEM.thirst = -10
ITEM.price = 5
ITEM.heal = 10
ITEM.cookable = true
ITEM.sound = "interface/inv_eat_can.ogg"