ITEM.name = "Salt & Vinegar Crisps"
ITEM.model = "models/griim/foodpack/crisps_saltandvinegar.mdl"
ITEM.description = "itemCrispsVinegarDesc"
ITEM.hunger = 40
ITEM.price = 60
ITEM.thirst = -5
ITEM.heal = 2
ITEM.sound = "interface/inv_eat_paperwrap.ogg"
ITEM.classes = nil