ITEM.name = "Canned Soup"
ITEM.model = "models/bioshockinfinite/canned_soup.mdl"
ITEM.description = "itemCannedDesc"
ITEM.hunger = 40
ITEM.thirst = 10
ITEM.price = 5
ITEM.empty = "empty_can"
ITEM.heal = 5
ITEM.cookable = true
ITEM.sound = "interface/inv_eat_can.ogg"