ITEM.name = "Canned Fish"
ITEM.model = "models/bioshockinfinite/cardine_can_open.mdl"
ITEM.description = "itemFishDesc"
ITEM.hunger = 30
ITEM.thirst = -10
ITEM.price = 15
ITEM.heal = 5
ITEM.cookable = true
ITEM.sound = "interface/inv_eat_can.ogg"