ITEM.name = "Meat Soup"
ITEM.model = "models/mosi/fallout4/props/food/squirrelsoup.mdl"
ITEM.description = "itemMeatSoupDesc"
ITEM.hunger = 35
ITEM.thirst = 10
ITEM.price = 25
ITEM.heal = 5
ITEM.cookable = true
ITEM.usenum = 2
ITEM.classes = nil