ITEM.name = "Onion Rings"
ITEM.model = "models/dead rising 2/onion_rings.mdl"
ITEM.description = "itemOnionRingsDesc"
ITEM.hunger = 35
ITEM.thirst = -10
ITEM.price = 15
ITEM.heal = 10
ITEM.cookable = true
ITEM.classes = nil