ITEM.name = "Orange Soda"
ITEM.model = "models/props_junk/garbage_plasticbottle003a.mdl"
ITEM.description = "itemOrangeSodaDesc"
ITEM.thirst = 25
ITEM.hunger = -10
ITEM.price = 8
ITEM.heal = 5
ITEM.sound = "interface/inv_drink_flask.ogg"
ITEM.usenum = 2
ITEM.isDrink = true