ITEM.name = "Pasta"
ITEM.model = "models/dead rising 2/pasta.mdl"
ITEM.description = "itemPastaDesc"
ITEM.hunger = 35
ITEM.thirst = -10
ITEM.price = 25
ITEM.heal = 10
ITEM.cookable = true
ITEM.empty = "misc_plate"
ITEM.classes = nil