ITEM.name = "Gelatinated Calorie Paste"
ITEM.model = Model("models/hls/alyxports/ration_box.mdl")
ITEM.description = "supplementsDesc"
ITEM.classes = nil
ITEM.hunger = 20
ITEM.thirst = 5
ITEM.price = 5
ITEM.sound = "interface/inv_eat_ration1.ogg"
ITEM.maxStack = 2