ITEM.name = "Vegetable Soup"
ITEM.model = "models/mosi/fallout4/props/food/vegetablesoup.mdl"
ITEM.description = "itemVegetableSoupDesc"
ITEM.hunger = 27
ITEM.thirst = 15
ITEM.price = 15
ITEM.usenum = 2
ITEM.heal = 5
ITEM.cookable = true
ITEM.classes = nil