ITEM.name = "Dirty Water"
ITEM.model = "models/synapse/alyxports/water_bottle_04_lid.mdl"
ITEM.description = "itemDirtyWaterDesc"
ITEM.class = nil
ITEM.thirst = 25
ITEM.hunger = -100
ITEM.price = 5
ITEM.sound = "interface/inv_drink_tea.ogg"
ITEM.isDrink = true